name: astroml
channels:
  - anaconda
  - astropy
  - conda-forge

dependencies:
  - astropy=2.0.4
  - python=3.5
  - numpy=1.13.1
  - matplotlib=2.0.2
  - scipy=0.19.1
  - scikit-learn=0.19.0
  - jupyter=1.0.0
  - pip:
    - astroML==0.3
